config/routes.rb
Rails.application.routes.draw do
  resources :services
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "services#index"
  resources :services, controller: 'services', only: [:index, :show,:edit, :update, :new, :destroy]

end

app/views/services_old/_form.html.erb
<%= form_with(model: service, local: true) do |form| %>
  <% if service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mb-2">
    <%= form.label :ccs_service_id, class: "col-sm-3 col-form-label" %>
    <%= form.text_field :ccs_service_id %>
  </div>

  <div class="form-group mb-2">
    <%= form.label :api_dom, class: "col-sm-3 col-form-label" %>
    <%= form.text_field :api_dom %>
  </div>

  <%= format_hash(@service_profile.to_hash, '') %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/services_old/_search.html.erb
<div class="table-responsive">
  <div class="divTableBodyWrapper">
    <div class="divTableHeading">
      <div class="divTableRow">

        <div class="divTableCell">
          <h1>Service</h1>
        </div>
        <div class="divTableCell">
        </div>
      </div>

      <%= form_with( url: new_service_path, method: :get, :local => true) do %>
        <div class="divTableRow">
          <div class="divTableCell">
            <div class="divTableHead"><%= label_tag(:ccs_service_id, "Service Id") %>
            </div>
          </div>
          <div class="divTableCell">
            <div class="divTableHead">
              <%= text_field_tag("service[ccs_service_id]") %>
            </div>
          </div>
          <div class="divTableCell"></div>
          <div class="divTableCell"><%= submit_tag("Search") %></div>
        </div>
      <%end %>
    </div>
  </div>
</div>

app/views/services_old/edit.html.erb
<h1>Editing Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services_old/index.html.erb
<div class="container my-3">  
  <p id="notice"><%= notice %></p>
  <p id="alert"><%= alert %></p>
  <div id="accordion">
    <div class="card">
      <div class="card-header" id="headingOne">
        <h5 class="mb-0">
          <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            Address
          </button>
        </h5>
      </div>
      <p id="notice"><%= notice %></p>

      <h1>Services</h1>

      <table>
        <thead>
          <tr>
            <th>Ccs service</th>
            <th>Api dom</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @services.each do |service| %>
            <tr>
              <td><%= service.ccs_service_id %></td>
              <td><%= service.api_dom %></td>
              <td><%= link_to 'Show', service %></td>
              <td><%= link_to 'Edit', edit_service_path(service) %></td>
              <td><%= link_to 'Destroy', service, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>
      <%= render partial: 'search' %>
      <% #= link_to 'New Service', new_service_path %>
    </div>
  </div>
</div>

app/views/services_old/new.html.erb
<h1>New Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Back', services_path %>

app/views/services_old/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ccs service:</strong>
  <%= @service.ccs_service_id %>
</p>

<p>
  <strong>Api dom:</strong>
  <%= @service.api_dom %>
</p>

<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>

<%= format_hash(@service_profile.to_hash, '', @readonly = true) %>